# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e85437898a7d4ab6920f95601edfa54abd89ec78730d8c3e15e86f1360c867ea946d3b75f865dbd796fa590b88a0cbd15aeb59eff48929c814d3c54b08ee2166

test:
  secret_key_base: 1dd02edeaa94d3a7deaa5b1d8a029a7d7444b4395564c636c27a0e6a641f4c289290603c633f3a68eb40582e128d1ec43db120248268211324520ab37e3a1119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
