# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67b0d240295a626135e12b172bcc006043d892d77f4de0f25198c5661a7755453c882cb2225c4ed1f6294752ebcc921f0569452c8ffa15113168361703411d5

test:
  secret_key_base: 191b6bd7e59ef065cf5f791abdf89578b3ee48e1873dbbc783a3d0e34b63f65f334a0f70763efeca1f0298b50686fca366060f5b0da9d6d20bad46a01d43066e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
